name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: ip add
        run: ifconfig

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker compose -f docker-compose.yml build
      - name: Build Docker running
        run: docker compose -f docker-compose.yml up -d
      - name: rerun docker
        run: docker compose -f docker-compose.yml up -d
      - name: Build Docker image
        run: docker ps    
      - name: Wait for frontend
        run: |
          for i in {1..15}; do
          if curl -s http://localhost:5173 > /dev/null; then
          echo "Frontend is up!"
          exit 0
          fi
          echo "Waiting for frontend..."
          sleep 3
          done
          echo "Frontend failed to start" && exit 1
